//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LythumOSL.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LythumOSL.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; Not exist!.
        /// </summary>
        internal static string IO_ERROR_FILE_NOT_EXIST {
            get {
                return ResourceManager.GetString("IO_ERROR_FILE_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK [0].
        /// </summary>
        internal static string MAPI_MSG_00 {
            get {
                return ResourceManager.GetString("MAPI_MSG_00", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User abort [1].
        /// </summary>
        internal static string MAPI_MSG_01 {
            get {
                return ResourceManager.GetString("MAPI_MSG_01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General MAPI failure [2].
        /// </summary>
        internal static string MAPI_MSG_02 {
            get {
                return ResourceManager.GetString("MAPI_MSG_02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAPI login failure [3].
        /// </summary>
        internal static string MAPI_MSG_03 {
            get {
                return ResourceManager.GetString("MAPI_MSG_03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disk full [4].
        /// </summary>
        internal static string MAPI_MSG_04 {
            get {
                return ResourceManager.GetString("MAPI_MSG_04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient memory [5].
        /// </summary>
        internal static string MAPI_MSG_05 {
            get {
                return ResourceManager.GetString("MAPI_MSG_05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied [6].
        /// </summary>
        internal static string MAPI_MSG_06 {
            get {
                return ResourceManager.GetString("MAPI_MSG_06", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -unknown- [7].
        /// </summary>
        internal static string MAPI_MSG_07 {
            get {
                return ResourceManager.GetString("MAPI_MSG_07", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many sessions [8].
        /// </summary>
        internal static string MAPI_MSG_08 {
            get {
                return ResourceManager.GetString("MAPI_MSG_08", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many files were specified [9].
        /// </summary>
        internal static string MAPI_MSG_09 {
            get {
                return ResourceManager.GetString("MAPI_MSG_09", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many recipients were specified [10].
        /// </summary>
        internal static string MAPI_MSG_10 {
            get {
                return ResourceManager.GetString("MAPI_MSG_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A specified attachment was not found [11].
        /// </summary>
        internal static string MAPI_MSG_11 {
            get {
                return ResourceManager.GetString("MAPI_MSG_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment open failure [12].
        /// </summary>
        internal static string MAPI_MSG_12 {
            get {
                return ResourceManager.GetString("MAPI_MSG_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment write failure [13].
        /// </summary>
        internal static string MAPI_MSG_13 {
            get {
                return ResourceManager.GetString("MAPI_MSG_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown recipient [14].
        /// </summary>
        internal static string MAPI_MSG_14 {
            get {
                return ResourceManager.GetString("MAPI_MSG_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad recipient type [15].
        /// </summary>
        internal static string MAPI_MSG_15 {
            get {
                return ResourceManager.GetString("MAPI_MSG_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No messages [16].
        /// </summary>
        internal static string MAPI_MSG_16 {
            get {
                return ResourceManager.GetString("MAPI_MSG_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid message [17].
        /// </summary>
        internal static string MAPI_MSG_17 {
            get {
                return ResourceManager.GetString("MAPI_MSG_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text too large [18].
        /// </summary>
        internal static string MAPI_MSG_18 {
            get {
                return ResourceManager.GetString("MAPI_MSG_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid session [19].
        /// </summary>
        internal static string MAPI_MSG_19 {
            get {
                return ResourceManager.GetString("MAPI_MSG_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type not supported [20].
        /// </summary>
        internal static string MAPI_MSG_20 {
            get {
                return ResourceManager.GetString("MAPI_MSG_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A recipient was specified ambiguously [21].
        /// </summary>
        internal static string MAPI_MSG_21 {
            get {
                return ResourceManager.GetString("MAPI_MSG_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message in use [22].
        /// </summary>
        internal static string MAPI_MSG_22 {
            get {
                return ResourceManager.GetString("MAPI_MSG_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network failure [23].
        /// </summary>
        internal static string MAPI_MSG_23 {
            get {
                return ResourceManager.GetString("MAPI_MSG_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid edit fields [24].
        /// </summary>
        internal static string MAPI_MSG_24 {
            get {
                return ResourceManager.GetString("MAPI_MSG_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid recipients [25].
        /// </summary>
        internal static string MAPI_MSG_25 {
            get {
                return ResourceManager.GetString("MAPI_MSG_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported [26].
        /// </summary>
        internal static string MAPI_MSG_26 {
            get {
                return ResourceManager.GetString("MAPI_MSG_26", resourceCulture);
            }
        }
    }
}
