//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LythumOSL.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LythumOSL.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ||| Sekantis mėnuo.
        /// </summary>
        public static string DateRangeNextMonth {
            get {
                return ResourceManager.GetString("DateRangeNextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to || Sekanti savaitė.
        /// </summary>
        public static string DateRangeNextWeek {
            get {
                return ResourceManager.GetString("DateRangeNextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |||| Sekantys metai.
        /// </summary>
        public static string DateRangeNextYear {
            get {
                return ResourceManager.GetString("DateRangeNextYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ||| Praėjęs mėnuo.
        /// </summary>
        public static string DateRangePreviousMonth {
            get {
                return ResourceManager.GetString("DateRangePreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to || Praėjusi savaitė.
        /// </summary>
        public static string DateRangePreviousWeek {
            get {
                return ResourceManager.GetString("DateRangePreviousWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |||| Praėję metai.
        /// </summary>
        public static string DateRangePreviousYear {
            get {
                return ResourceManager.GetString("DateRangePreviousYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ||| Šis mėnuo.
        /// </summary>
        public static string DateRangeThisMonth {
            get {
                return ResourceManager.GetString("DateRangeThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to || Ši savaitė.
        /// </summary>
        public static string DateRangeThisWeek {
            get {
                return ResourceManager.GetString("DateRangeThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to |||| Šie metai.
        /// </summary>
        public static string DateRangeThisYear {
            get {
                return ResourceManager.GetString("DateRangeThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Šiandien.
        /// </summary>
        public static string DateRangeToday {
            get {
                return ResourceManager.GetString("DateRangeToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Rytoj.
        /// </summary>
        public static string DateRangeTomorrow {
            get {
                return ResourceManager.GetString("DateRangeTomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | Vakar.
        /// </summary>
        public static string DateRangeYesterday {
            get {
                return ResourceManager.GetString("DateRangeYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection info.
        /// </summary>
        public static string LabelConnectionInfo {
            get {
                return ResourceManager.GetString("LabelConnectionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string LabelCopy {
            get {
                return ResourceManager.GetString("LabelCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed.
        /// </summary>
        public static string LabelError {
            get {
                return ResourceManager.GetString("LabelError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string LabelOk {
            get {
                return ResourceManager.GetString("LabelOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        public static string LabelQuestion {
            get {
                return ResourceManager.GetString("LabelQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User&apos;s info.
        /// </summary>
        public static string LabelUserInfo {
            get {
                return ResourceManager.GetString("LabelUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LabelUsername {
            get {
                return ResourceManager.GetString("LabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string LabelWarning {
            get {
                return ResourceManager.GetString("LabelWarning", resourceCulture);
            }
        }
    }
}
