//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LythumOSL.Security.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LythumOSL.Security.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aes::DecryptData failure.
        /// </summary>
        internal static string ENC_ERROR_DECRYPT {
            get {
                return ResourceManager.GetString("ENC_ERROR_DECRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aes::EncryptData failure.
        /// </summary>
        internal static string ENC_ERROR_ENCRYPT {
            get {
                return ResourceManager.GetString("ENC_ERROR_ENCRYPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a certificate that does not contain a private key for security purposes.
        /// </summary>
        internal static string ENC_ERROR_HAS_PRIVATE_KEY {
            get {
                return ResourceManager.GetString("ENC_ERROR_HAS_PRIVATE_KEY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate key was not in the expected format.
        /// </summary>
        internal static string ENC_ERROR_INVALID_KEY_FORMAT {
            get {
                return ResourceManager.GetString("ENC_ERROR_INVALID_KEY_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The IV must be exactally 128 bits long.
        /// </summary>
        internal static string ENC_ERROR_IV128_LENGTH {
            get {
                return ResourceManager.GetString("ENC_ERROR_IV128_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Key must be exactally 256 bits long.
        /// </summary>
        internal static string ENC_ERROR_KEY256_LENGTH {
            get {
                return ResourceManager.GetString("ENC_ERROR_KEY256_LENGTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading the certificate.
        /// </summary>
        internal static string ENC_ERROR_READ_CERT {
            get {
                return ResourceManager.GetString("ENC_ERROR_READ_CERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The RSA engine has not been initialized with a certificate yet.
        /// </summary>
        internal static string ENC_ERROR_RSA_NOT_INITIALIZED {
            get {
                return ResourceManager.GetString("ENC_ERROR_RSA_NOT_INITIALIZED", resourceCulture);
            }
        }
    }
}
