//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.5485
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LythumOSL.Reporting.CR.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LythumOSL.Reporting.CR.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopijų skaičius.
        /// </summary>
        internal static string FrmReport_CopiesCount {
            get {
                return ResourceManager.GetString("FrmReport_CopiesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksportas atliktas!.
        /// </summary>
        internal static string FrmReport_ExportFinished {
            get {
                return ResourceManager.GetString("FrmReport_ExportFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasirinkite katalogą į kur eksportuoti.
        /// </summary>
        internal static string FrmReport_ExportFolderTitle {
            get {
                return ResourceManager.GetString("FrmReport_ExportFolderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Word *.doc.
        /// </summary>
        internal static string FrmReport_ExportFormat_DOC {
            get {
                return ResourceManager.GetString("FrmReport_ExportFormat_DOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MS Excel *.xls.
        /// </summary>
        internal static string FrmReport_ExportFormat_Excel {
            get {
                return ResourceManager.GetString("FrmReport_ExportFormat_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTML.
        /// </summary>
        internal static string FrmReport_ExportFormat_HTML {
            get {
                return ResourceManager.GetString("FrmReport_ExportFormat_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adobe *.pdf.
        /// </summary>
        internal static string FrmReport_ExportFormat_PDF {
            get {
                return ResourceManager.GetString("FrmReport_ExportFormat_PDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rich text *.rtf.
        /// </summary>
        internal static string FrmReport_ExportFormat_RTF {
            get {
                return ResourceManager.GetString("FrmReport_ExportFormat_RTF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spausdinti visus.
        /// </summary>
        internal static string FrmReport_PrintAll {
            get {
                return ResourceManager.GetString("FrmReport_PrintAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spausdinti pažymėtą.
        /// </summary>
        internal static string FrmReport_PrintSelected {
            get {
                return ResourceManager.GetString("FrmReport_PrintSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopijų skaičius.
        /// </summary>
        internal static string FrmReports_CopiesCount {
            get {
                return ResourceManager.GetString("FrmReports_CopiesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eksportuoti pažymėtus.
        /// </summary>
        internal static string FrmReports_ExportSelected {
            get {
                return ResourceManager.GetString("FrmReports_ExportSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pavadinimas.
        /// </summary>
        internal static string FrmReports_Name {
            get {
                return ResourceManager.GetString("FrmReports_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spausdinti visus.
        /// </summary>
        internal static string FrmReports_PrintAll {
            get {
                return ResourceManager.GetString("FrmReports_PrintAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spausdinti pažymėtus.
        /// </summary>
        internal static string FrmReports_PrintSelected {
            get {
                return ResourceManager.GetString("FrmReports_PrintSelected", resourceCulture);
            }
        }
    }
}
